export const NAME = 'PROJECT';

export const ON_CREATE_SUCCESS = `${NAME}/ON_CREATE_SUCCESS`;
export const ON_LOAD_ALL = `${NAME}/ON_LOAD_ALL`;
export const ON_LOAD_PROJECT_TO_EDIT = `${NAME}/ON_LOAD_PROJECT_TO_EDIT`;
export const ON_UPDATE_SUCCESS = `${NAME}/ON_UPDATE_SUCCESS`;
