export const NAME = 'TASK';

export const ON_CREATE_SUCCESS = `${NAME}/ON_CREATE_SUCCESS`;
export const ON_LOAD_SUCCESS = `${NAME}/ON_LOAD_SUCCESS`;
export const ON_UPDATE_SUCCESS = `${NAME}/ON_UPDATE_SUCCESS`;
